language: node_js

node_js:
  - '10'

before_script:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

before_deploy: 
  - git add . && git commit -m "."
  - npm version $TRAVIS_TAG

deploy:
  provider: npm
  email: tqfisher@iastate.edu
  api_key: $NPM_TOKEN
  on:
    tags: true